// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DetectGamePath() {
  return window['go']['main']['App']['DetectGamePath']();
}

export function FetchMods() {
  return window['go']['main']['App']['FetchMods']();
}

export function GetAvailableMods() {
  return window['go']['main']['App']['GetAvailableMods']();
}

export function GetGamePath() {
  return window['go']['main']['App']['GetGamePath']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function ResetGamePath() {
  return window['go']['main']['App']['ResetGamePath']();
}

export function SaveConfig() {
  return window['go']['main']['App']['SaveConfig']();
}

export function SetCustomGamePath(arg1) {
  return window['go']['main']['App']['SetCustomGamePath'](arg1);
}

export function SetGamePath(arg1) {
  return window['go']['main']['App']['SetGamePath'](arg1);
}
