// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function DetectGamePath():Promise<void>;

export function FetchMods():Promise<Array<main.ModData>>;

export function GetAvailableMods():Promise<Array<main.ModData>>;

export function GetGamePath():Promise<string>;

export function LoadConfig():Promise<void>;

export function ResetGamePath():Promise<void>;

export function SaveConfig():Promise<void>;

export function SetCustomGamePath(arg1:string):Promise<void>;

export function SetGamePath(arg1:context.Context):Promise<void>;
